# Generated by Django 3.2.20 on 2023-08-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_hobby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='student.Hobby'),
        ),
    ]
